In [1]:
from venmo_scrape import Venmo_Scrape_Client
import pandas as pd
import config

In [2]:

access_token = Venmo_Scrape_Client.get_access_token(username = config.username,
                                        password = config.password, device_id = config.device_id)

scrape = Venmo_Scrape_Client(access_token = access_token)



my_user = scrape.user.get_my_profile()

IMPORTANT: Take a note of your device id to avoid 2-Factor-Authentication for your next login.
device-id: 86354220-15D2-2O45-00U6-3WJ02V247RQ9
IMPORTANT: Your Access Token will never expire, unless you logout using it. Take a note of it for your future use or even for logging out, you will need it.

Successfully logged in.
access_token: b65d17c7f2140515cc33dc0eba26c236584aba3c101003779dea93ba4f949032

In [3]:
user_df = pd.DataFrame(scrape.user_scrape(user_id = my_user.id), index = [0])
user_df

,username,first_name,last_name,user_id,phone,profile_picture_url,is_active
0,Mike-Sender,Mike,Sender,1350836974256128854,18625209661,https://pics.venmo.com/9f06a2b5-5cf1-4a20-a15e...,True

In [4]:
transactions, users_initial = scrape.user_transaction_scrape(user_id = my_user.id)
transactions, users_initial

([<venmo_api.models.transaction.Transaction at 0x5dc97f0>,
  <venmo_api.models.transaction.Transaction at 0xd28fdd8>,
  <venmo_api.models.transaction.Transaction at 0xd2b9580>,
  <venmo_api.models.transaction.Transaction at 0xd2b9850>,
  <venmo_api.models.transaction.Transaction at 0xd2b96b8>,
  <venmo_api.models.transaction.Transaction at 0xd2b9aa8>,
  <venmo_api.models.transaction.Transaction at 0xd2b9b38>,
  <venmo_api.models.transaction.Transaction at 0xd2b9b50>,
  <venmo_api.models.transaction.Transaction at 0xd2b9b80>,
  <venmo_api.models.transaction.Transaction at 0xd2b9d00>,
  <venmo_api.models.transaction.Transaction at 0xd2b9cd0>,
  <venmo_api.models.transaction.Transaction at 0xd2b9da8>,
  <venmo_api.models.transaction.Transaction at 0xd2b9e38>,
  <venmo_api.models.transaction.Transaction at 0xd2b9ef8>,
  <venmo_api.models.transaction.Transaction at 0xd2b9fb8>,
  <venmo_api.models.transaction.Transaction at 0xd37e0a0>,
  <venmo_api.models.transaction.Transaction at 0xd37e160>,
  <venmo_api.models.transaction.Transaction at 0xd37e220>,
  <venmo_api.models.transaction.Transaction at 0xd37e2e0>,
  <venmo_api.models.transaction.Transaction at 0xd37e3a0>,
  <venmo_api.models.transaction.Transaction at 0xd37e460>,
  <venmo_api.models.transaction.Transaction at 0xd37e520>,
  <venmo_api.models.transaction.Transaction at 0xd37e5e0>,
  <venmo_api.models.transaction.Transaction at 0xd37e6a0>,
  <venmo_api.models.transaction.Transaction at 0xd37e760>,
  <venmo_api.models.transaction.Transaction at 0xd37e820>,
  <venmo_api.models.transaction.Transaction at 0xd37e8e0>,
  <venmo_api.models.transaction.Transaction at 0xd37e9a0>,
  <venmo_api.models.transaction.Transaction at 0xd37ea60>,
  <venmo_api.models.transaction.Transaction at 0xd37eb20>,
  <venmo_api.models.transaction.Transaction at 0xd37ebe0>,
  <venmo_api.models.transaction.Transaction at 0xd37eca0>,
  <venmo_api.models.transaction.Transaction at 0xd37ed60>,
  <venmo_api.models.transaction.Transaction at 0xd37ee20>,
  <venmo_api.models.transaction.Transaction at 0xd37eee0>,
  <venmo_api.models.transaction.Transaction at 0xd37efa0>,
  <venmo_api.models.transaction.Transaction at 0xd380088>,
  <venmo_api.models.transaction.Transaction at 0xd380148>,
  <venmo_api.models.transaction.Transaction at 0xd380208>,
  <venmo_api.models.transaction.Transaction at 0xd3802c8>,
  <venmo_api.models.transaction.Transaction at 0xd380388>,
  <venmo_api.models.transaction.Transaction at 0xd380448>,
  <venmo_api.models.transaction.Transaction at 0xd380508>,
  <venmo_api.models.transaction.Transaction at 0xd3805c8>,
  <venmo_api.models.transaction.Transaction at 0xd380688>,
  <venmo_api.models.transaction.Transaction at 0xd380748>,
  <venmo_api.models.transaction.Transaction at 0xd380808>,
  <venmo_api.models.transaction.Transaction at 0xd3808c8>,
  <venmo_api.models.transaction.Transaction at 0xd380988>],
 {'1211798632005632671',
  '1324732003647488965',
  '1350836974256128854',
  '1373268523089920988',
  '1539091850067968476',
  '1545098168893440136',
  '1554742132080640116',
  '1588806775996416333',
  '1608773021990912422',
  '1626820600397824398',
  '1648062434902016149',
  '1700438235676672478',
  '1705324474007552775',
  '1723448061591552445',
  '1839913733455872495',
  '1958692563976192834'})

In [17]:
transaction_set = {transaction.id for transaction in transactions[:1]}

transaction_df = pd.DataFrame(scrape.transaction_scrape(transactions[0]),index = [0])
transaction_df, transaction_set

(              actor_id  date_completed  date_created   note  \
 0  1324732003647488965      1594792774    1594792774  Meats

              target_id       transaction_id
 0  1350836974256128854  3053540337977917900  ,
 {'3053540337977917900'})

In [14]:
transaction_df = transaction_df.append(scrape.transaction_scrape(transactions[1]), ignore_index = True)
transaction_df

,actor_id,date_completed,date_created,note,target_id,transaction_id
0,1324732003647488965,1594792774,1594792774,Meats,1350836974256128854,3053540337977917900
1,1350836974256128854,1593708816,1593708816,🏕🌚🏆🔮,1545098168893440136,3044447444378059725

In [7]:
user_df = user_df.append(scrape.user_scrape(user_id = '1626820600397824398'), ignore_index = True)

In [8]:
user_df

,username,first_name,last_name,user_id,phone,profile_picture_url,is_active
0,Mike-Sender,Mike,Sender,1350836974256128854,18625209661,https://pics.venmo.com/9f06a2b5-5cf1-4a20-a15e...,True
1,Alex-Dagley,Alex,Dagley,1626820600397824398,None,https://pics.venmo.com/e71e462f-c37b-4819-ae9e...,True

In [18]:
for transaction in transactions:
    if transaction.id not in transaction_set:
        transaction_df = transaction_df.append(scrape.transaction_scrape(transaction), ignore_index = True)
        transaction_set = transaction_set.union(transaction.id)

In [19]:
transaction_df

,actor_id,date_completed,date_created,note,target_id,transaction_id
0,1324732003647488965,1594792774,1594792774,Meats,1350836974256128854,3053540337977917900
1,1350836974256128854,1593708816,1593708816,🏕🌚🏆🔮,1545098168893440136,3044447444378059725
2,1539091850067968476,1593341361,1593341361,👩‍👦‍👦❤️,1350836974256128854,3041365002033299544
3,1211798632005632671,1593204265,1593204265,Gifts for parents,1350836974256128854,3040214962120163729
4,1350836974256128854,1593203264,1593203264,I hope are parents love us,1554742132080640116,3040206561239630271
5,1350836974256128854,1593202988,1593202988,Justiceashealing.org,1608773021990912422,3040204245396619949
6,1839913733455872495,1593038884,1593038884,recycling bags,1350836974256128854,3038827643970519650
7,1350836974256128854,1593022961,1593022961,Lost 💽,1648062434902016149,3038694075814380200
8,1324732003647488965,1593022936,1593022935,"Greens, Parm, sage",1350836974256128854,3038693859639951485
9,1839913733455872495,1592940419,1592940419,rice and draino mmmmm,1350836974256128854,3038001658408731356
10,1350836974256128854,1592895904,1592895904,🎱,1839913733455872495,3037628244707771315
11,1350836974256128854,1592895837,1592895837,🤑♠️♥️♠️♣️♠️♦️,1839913733455872495,3037627676958392358
12,1350836974256128854,1591996394,1591996394,:🤑🗽🌉🌁,1839913733455872495,3030082607061664560
13,1958692563976192834,1591814278,1591814278,Beks bday,1350836974256128854,3028554902126199768
14,1839913733455872495,1591814263,1591814263,wine baybayyyy,1350836974256128854,3028554782110384907
15,1839913733455872495,1591573998,1591573998,CVS,1350836974256128854,3026539286422880649
16,1839913733455872495,1591573996,1591573996,can i still do this if i left early,1350836974256128854,3026539270727795568
17,1350836974256128854,1591573854,1591573854,Tolls 🤑 🎢,1839913733455872495,3026538080250102650
18,1350836974256128854,1591045535,1591045535,June rent,1373268523089920988,3022106219813798786
19,1350836974256128854,1591042595,1591042595,🤑,1839913733455872495,3022081560913379484
20,1350836974256128854,1590437855,1590437855,🃏,1700438235676672478,3017008631485825803
21,1723448061591552445,1590386752,1590386752,💩,1350836974256128854,3016579950732903359
22,1545098168893440136,1589787019,1589787019,🍕😋,1350836974256128854,3011549026379104343
23,1350836974256128854,1589783884,1589783884,🦈,1839913733455872495,3011522725333172771
24,1350836974256128854,1589783800,1589783800,11328,1839913733455872495,3011522023626113256
25,1350836974256128854,1589686070,1589686070,:🦈,1626820600397824398,3010702201837322419
26,1211798632005632671,1589230413,1589230413,Mom day,1350836974256128854,3006879874963997296
27,1539091850067968476,1589149626,1589149626,🐣,1350836974256128854,3006202185219310271
28,1554742132080640116,1589149371,1589149371,Mothers day,1350836974256128854,3006200041804136798
29,1839913733455872495,1588791405,1588791405,April ConEd 😩,1350836974256128854,3003197210092372264
30,1839913733455872495,1588791403,1588791403,coffee beanies,1350836974256128854,3003197192241414551
31,1350836974256128854,1588574024,1588574024,🦈,1839913733455872495,3001373686994305612
32,1350836974256128854,1588490109,1588490109,🦈,1588806775996416333,3000669753439159024
33,1588806775996416333,1588016522,1588016522,Ace King,1350836974256128854,2996697015250846560
34,1839913733455872495,1588010590,1588010590,"your spoils, m’doid",1350836974256128854,2996647255219372160
35,1839913733455872495,1588010537,1588010537,hooker’s dollar,1350836974256128854,2996646808861540857
36,1723448061591552445,1587973469,1587973469,🦈,1350836974256128854,2996335862213509653
37,1839913733455872495,1587583614,1587583614,new puzz,1350836974256128854,2993065521978540595
38,1350836974256128854,1587500756,1587500756,🤑,1839913733455872495,2992370460894691464
39,1839913733455872495,1587428331,1587428331,March & April Internet ☺️,1350836974256128854,2991762914383233612
40,1839913733455872495,1587427286,1587427286,March ConEd 💰👋🏻,1350836974256128854,2991754149378392769
41,1350836974256128854,1587179693,1587179693,👵,1839913733455872495,2989677189537989297
42,1839913733455872495,1587177912,1587177912,toll time,1350836974256128854,2989662249578136228
43,1350836974256128854,1586987100,1586987100,😷🤑 groceries 4/15,1839913733455872495,2988061597047455811
44,1839913733455872495,1586486976,1586486976,groceries on 4/7,1350836974256128854,2983866254210630274
45,1350836974256128854,1586395432,1586395431,Fun night out!,1705324474007552775,2983098325709882017
46,1839913733455872495,1586391966,1586391966,case of🍷,1350836974256128854,2983069257211838857
47,1839913733455872495,1585600168,1585600168,Feb Internet,1350836974256128854,2976427175466500862
48,1350836974256128854,1585599489,1585599489,🥫🥫🥫IKEA 🥫🥫🥫,1839913733455872495,2976421472513294354

In [24]:
users_is = {transaction.target.id for transaction in transactions}.union(
                                {transaction.actor.id for transaction in transactions})

In [25]:
len(users_ts), len(users_is)

(98, 16)

In [ ]:
scrape.log_out(f'Bearer {access_token}')